version: '3.9'

namespace:
  services:
    backend:
      build: ../backend
      ports:
        - "5000:5000"
      volumes:
        - ../backend:/app
      command: python app.py
      depends_on:
        - ml_service
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 10s
      env_file:
        - ../backend/.env

    ml_service:
      build: ../ml_service
      ports:
        - "8500:8500"
      volumes:
        - ../ml_service:/app
      command: python model.py
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8500/ || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 10s
      env_file:
        - ../ml_service/.env

    frontend:
      build: ../frontend
      ports:
        - "127.0.0.1:3000:3000"
      volumes:
        - ../frontend:/app
      command: npm start
      depends_on:
        - backend
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 10s
      env_file:
        - ../frontend/.env
