version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
    command: python app.py
    depends_on:
      ml_service:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - ../backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ml_service:
    build: ../ml_service
    ports:
      - "8500:8500"
    volumes:
      - ../ml_service:/app
    command: python model.py
    restart: unless-stopped
    env_file:
      - ../ml_service/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8500/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ../frontend
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ../frontend:/app
    command: npm start
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - ../frontend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
