"""initial migration

Revision ID: 73c411aaf332
Revises: 
Create Date: 2025-06-17 21:02:46.882704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c411aaf332'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_worklog_project', 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key('fk_worklog_developer', 'developers', ['developer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_worklog_developer', type_='foreignkey')
        batch_op.drop_constraint('fk_worklog_project', type_='foreignkey')

    # ### end Alembic commands ###
